jwt:
  #jwt的请求头——与前端一致，放置在header中
  headerKey: Authorization
  #jwt请求部前缀——与前端一致
  headerPrefix: Bearer
  #过期时间
  expirationTime: 300000
  #刷新token过期时间
  refreshTokenTime: 14400000
  #密钥——上线时需要更改随机数字
  secretKey: secret
  #不用拦截验证的路径
  noVerifPath:
    - /login
    - /otherPath